name: rent_right_place
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1 # 新增這行，版本號可能會更新，建議使用最新穩定版
  google_maps_flutter: ^2.8.0 # 更新到最新穩定版
  geocoding: ^4.0.0 # 更新到最新穩定版
  proj4dart: ^2.1.0 # 新增投影轉換套件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/TpeMrtStations_TWD97_FIDCODE.json
    - assets/taipei_medical_facilities.json # Added this line
